### ISSUE TITLE
Erro na endpoint /api/v1/course

### ISSUE THREAD

**Issue by wantero** [NewSchoolBR/newschool-backend#92]
Ao logar na plataforma, está ocorrendo o seguinte erro nos ambiente de QA e DEV:

![Screenshot from 2020-01-19 06-49-22](https://user-images.githubusercontent.com/12854717/72678792-e67a6b80-3a87-11ea-9b68-b8f9a9c21bb2.png)

`2020-01-19T09:47:46.549314+00:00 heroku[router]: at=info method=GET path="/api/v1/course" host=newschoolbrapi-qa.herokuapp.com request_id=a5a99997-0b03-41e0-b701-3f2f3e254328 fwd="189.110.170.166" dyno=web.1 connect=1ms service=204ms status=500 bytes=310 protocol=https
2020-01-19T09:47:46.549046+00:00 app[web.1]: [31m[Nest] 70   - [39m01/19/2020, 9:47:46 AM   [38;5;3m[ExceptionsHandler] [39m[31mER_BAD_FIELD_ERROR: Unknown column 'Course.authorName' in 'field list'[39m[38;5;3m +1011ms[39m
2020-01-19T09:47:46.549106+00:00 app[web.1]: QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'Course.authorName' in 'field list'
2020-01-19T09:47:46.549109+00:00 app[web.1]:     at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:11:28)
2020-01-19T09:47:46.549111+00:00 app[web.1]:     at Query.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:170:45)
2020-01-19T09:47:46.549114+00:00 app[web.1]:     at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:525:10)
2020-01-19T09:47:46.549116+00:00 app[web.1]:     at Query._callback (/app/node_modules/mysql/lib/Connection.js:491:16)
2020-01-19T09:47:46.549118+00:00 app[web.1]:     at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
2020-01-19T09:47:46.549120+00:00 app[web.1]:     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
2020-01-19T09:47:46.549122+00:00 app[web.1]:     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
2020-01-19T09:47:46.549124+00:00 app[web.1]:     at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
2020-01-19T09:47:46.549126+00:00 app[web.1]:     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
2020-01-19T09:47:46.549129+00:00 app[web.1]:     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)`

**Comment by wantero** [comment]
Foram recriados os dois banco de dados (DEV e QA).
